GET  http://localhost:5110/players
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImVtbWEiLCJzdWIiOiJlbW1hIiwianRpIjoiZWVmOGY5YjEiLCJyb2xlIjoiYWRtaW4iLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo0NDEyMSIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzA5IiwiaHR0cDovL2xvY2FsaG9zdDo1MTEwIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzEzMiJdLCJuYmYiOjE3Mzc4MzYzMTcsImV4cCI6MTc0NTYxMjMxNywiaWF0IjoxNzM3ODM2MzE4LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.bfwsEbuvuMgIIbSefCXtbQM0lrVAejyJUUIMVgIkkvc

###
GET http://localhost:5110/mygames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBsYXllcjEiLCJzdWIiOiJwbGF5ZXIxIiwianRpIjoiY2VkNTEyNjUiLCJyb2xlIjoicGxheWVyIiwic3Vic2NyaXB0aW9uIjoiZ29sZCIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjQ0MTIxIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMDkiLCJodHRwOi8vbG9jYWxob3N0OjUxMTAiLCJodHRwczovL2xvY2FsaG9zdDo3MTMyIl0sIm5iZiI6MTczNzg4MzY4MywiZXhwIjoxNzQ1NjU5NjgzLCJpYXQiOjE3Mzc4ODM2ODQsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.7ac1g8DZ0e2qSSVH3aukxo4YJZK7o7aehB7gZGrhw7g