GET  http://localhost:5110/players
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImVtbWEiLCJzdWIiOiJlbW1hIiwianRpIjoiZWVmOGY5YjEiLCJyb2xlIjoiYWRtaW4iLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo0NDEyMSIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzA5IiwiaHR0cDovL2xvY2FsaG9zdDo1MTEwIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzEzMiJdLCJuYmYiOjE3Mzc4MzYzMTcsImV4cCI6MTc0NTYxMjMxNywiaWF0IjoxNzM3ODM2MzE4LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.bfwsEbuvuMgIIbSefCXtbQM0lrVAejyJUUIMVgIkkvc

###
GET http://localhost:5110/mygames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBsYXllcjEiLCJzdWIiOiJwbGF5ZXIxIiwianRpIjoiMzNjYjllNiIsInJvbGUiOiJwbGF5ZXIiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo0NDEyMSIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzA5IiwiaHR0cDovL2xvY2FsaG9zdDo1MTEwIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzEzMiJdLCJuYmYiOjE3Mzc4Mzc3NTcsImV4cCI6MTc0NTYxMzc1NywiaWF0IjoxNzM3ODM3NzU4LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.JXWoxD8sZA9ePfsfZR02BJjrglsvE_zY_T5R3fURinY